package com.lu4p.fokuslauncher.ui.components

/**
 * Extra lowercase search tokens for icon picker filtering (beyond PascalCase name splits). Aimed at
 * everyday intents: "message" → send/chat, "globe" → Language, "pencil" → EditNote, etc.
 *
 * Keys are picker glyph names ([MinimalIcons.names]), including the legacy `send` entry.
 */
internal object IconPickerSearchAliases {
    val byIconName: Map<String, String> =
            mapOf(
                    // Messaging / mail
                    "send" to "message messages chat mail email sms text messenger telegram whatsapp",
                    "Chat" to "message messages messenger text talk conversation sms",
                    "ChatBubble" to "message messages messenger text talk chat sms",
                    "Sms" to "message messages text messenger chat sms",
                    "Mms" to "message messages text multimedia chat",
                    "Forum" to "message messages chat discussion community talk",
                    "Comment" to "message comment discuss feedback talk",
                    "ModeComment" to "message comment discuss talk",
                    "Email" to "message mail inbox envelope letter",
                    "Mail" to "message email inbox envelope letter",
                    "MarkEmailUnread" to "message mail email unread inbox",
                    "MarkChatUnread" to "message chat unread messenger",
                    "MarkAsUnread" to "message mail email unread inbox",
                    "MarkUnreadChatAlt" to "message chat unread messenger",
                    "Voicemail" to "message phone call voice",
                    "Campaign" to "announce megaphone marketing ads promotion",
                    "Share" to "send forward export social",
                    "Link" to "url hyperlink website attach",
                    "Inbox" to "mail email message mailbox",
                    "Outbox" to "mail email send message",
                    "Drafts" to "mail email draft compose",
                    "Archive" to "mail file store backup",
                    "Reply" to "message mail answer respond",
                    "ReplyAll" to "message mail answer respond",
                    "Forward" to "message mail send share",
                    "Quickreply" to "message chat reply respond",
                    "AlternateEmail" to "email at mention mail",
                    "Dialpad" to "phone keypad dial call",
                    "VideoChat" to "video call meet zoom facetime",
                    "VoiceChat" to "call talk voice message",

                    // Phone
                    "Call" to "phone dial telephone ring",
                    "Phone" to "call dial telephone mobile",
                    "PhoneInTalk" to "call phone dial talking",
                    "PhoneMissed" to "call phone missed",
                    "PhoneCallback" to "call phone callback return",
                    "Contacts" to "people address book phonebook",
                    "ContactMail" to "email people contact",
                    "ContactPhone" to "call people contact phone",

                    // Web / browser
                    "Language" to "globe world browser internet web translate",
                    "Public" to "globe world earth internet community",
                    "TravelExplore" to "globe world explore travel search",
                    "Web" to "browser internet www website",
                    "OpenInBrowser" to "browser internet www website",
                    "Translate" to "language dictionary interpret",

                    // Notes / writing
                    "EditNote" to "pen pencil note write notepad document edit",
                    "Draw" to "pen pencil write sketch paint art",
                    "StickyNote2" to "note sticky notepad reminder",
                    "Notes" to "note notepad write memo",
                    "NoteAlt" to "note notepad write memo",
                    "NoteAdd" to "note notepad write memo new",
                    "Description" to "document file text note page",
                    "Article" to "document file text news page blog",
                    "Summarize" to "document summary abstract notes",
                    "Assignment" to "task homework clipboard document",
                    "Task" to "todo checklist assignment work",
                    "Checklist" to "todo task list done",
                    "Book" to "read reading ebook library",
                    "MenuBook" to "read reading book cookbook",
                    "AutoStories" to "read reading book stories",
                    "Newspaper" to "news read article press",

                    // Time / calendar
                    "CalendarMonth" to "calendar date schedule agenda planner",
                    "CalendarToday" to "calendar date today schedule",
                    "Event" to "calendar date schedule appointment meeting",
                    "Schedule" to "calendar clock time appointment",
                    "Today" to "calendar date day",
                    "Alarm" to "clock wake reminder alert",
                    "Timer" to "clock countdown stopwatch",
                    "Snooze" to "alarm clock sleep delay",
                    "History" to "clock past recent time",
                    "Update" to "refresh upgrade new version",
                    "Sync" to "refresh reload update synchronize",
                    "Autorenew" to "refresh reload sync loop",

                    // Media
                    "MusicNote" to "audio song music spotify podcast",
                    "LibraryMusic" to "audio song music playlist album",
                    "Album" to "music audio record vinyl",
                    "Podcasts" to "audio radio episode listen",
                    "QueueMusic" to "playlist music audio queue",
                    "PlaylistPlay" to "playlist music audio play",
                    "PlaylistAdd" to "playlist music audio add",
                    "Radio" to "fm am broadcast audio listen",
                    "Headset" to "headphones audio music listen",
                    "Headphones" to "headset audio music listen",
                    "HeadsetMic" to "headphones microphone gaming",
                    "Earbuds" to "headphones airpods audio",
                    "Mic" to "microphone record voice audio podcast",
                    "MicOff" to "microphone mute silence",
                    "Videocam" to "video camera film record movie",
                    "VideocamOff" to "video camera off mute",
                    "VideoCall" to "video meet zoom facetime call",
                    "VideoLibrary" to "video youtube gallery films",
                    "Movie" to "film cinema video watch",
                    "Theaters" to "cinema film movie watch",
                    "PlayArrow" to "play media video music start",
                    "PlayCircle" to "play media video music start",
                    "Pause" to "pause media stop",
                    "Stop" to "stop media end",
                    "SkipNext" to "next track skip forward",
                    "SkipPrevious" to "previous track skip back",
                    "VolumeUp" to "sound audio speaker loud",
                    "VolumeOff" to "mute silence sound",
                    "Tv" to "television watch living room",
                    "LiveTv" to "television broadcast watch",
                    "Cast" to "chromecast stream tv mirror",
                    "Airplay" to "cast stream apple mirror",
                    "Slideshow" to "presentation photos gallery",
                    "CameraAlt" to "photo picture snapshot camera",
                    "PhotoCamera" to "photo picture snapshot camera",
                    "Photo" to "picture gallery image photos",
                    "PhotoLibrary" to "gallery pictures photos album",
                    "PhotoAlbum" to "gallery pictures photos album",
                    "Image" to "picture photo gallery",
                    "AddAPhoto" to "camera picture photo new",
                    "QrCode" to "scan barcode qr code",
                    "QrCode2" to "scan barcode qr code",
                    "QrCodeScanner" to "scan barcode qr code",

                    // Places / travel
                    "Map" to "maps navigation location gps",
                    "Place" to "location pin maps marker",
                    "LocationOn" to "place pin maps gps marker",
                    "Directions" to "navigation route maps",
                    "Navigation" to "directions compass maps gps",
                    "Explore" to "compass discover maps",
                    "Flight" to "airplane plane travel airport",
                    "FlightTakeoff" to "airplane plane depart airport",
                    "FlightLand" to "airplane plane arrive airport",
                    "AirplaneTicket" to "flight plane travel boarding",
                    "DirectionsCar" to "car drive auto vehicle",
                    "DirectionsBus" to "bus transit transport",
                    "DirectionsBike" to "bike bicycle cycle",
                    "DirectionsWalk" to "walk pedestrian on foot",
                    "DirectionsRun" to "run jog fitness",
                    "PedalBike" to "bike bicycle cycle",
                    "TwoWheeler" to "motorcycle scooter bike",
                    "ElectricCar" to "ev electric vehicle charging",
                    "Train" to "rail transit transport",
                    "Subway" to "metro transit underground",
                    "Tram" to "streetcar transit rail",
                    "LocalTaxi" to "cab rideshare uber lyft",
                    "LocalShipping" to "delivery truck package shipping",
                    "CarRental" to "car hire vehicle",
                    "Commute" to "travel work transit",
                    "Hotel" to "stay lodging travel sleep",
                    "Apartment" to "home housing flat building",
                    "Cottage" to "home house cabin",
                    "House" to "home housing",
                    "Home" to "house main start",
                    "Bed" to "sleep hotel bedroom",
                    "Luggage" to "suitcase travel baggage",
                    "Museum" to "culture art gallery visit",
                    "Church" to "religion worship christian",
                    "Mosque" to "religion worship islam",
                    "MyLocation" to "gps location pinpoint",
                    "NearMe" to "nearby location around",
                    "Traffic" to "cars congestion road",

                    // Food / shop
                    "Restaurant" to "food eat dining meal",
                    "LocalCafe" to "coffee cafe drink",
                    "Coffee" to "cafe drink espresso",
                    "LocalBar" to "drink alcohol cocktail pub",
                    "LocalPizza" to "food pizza eat",
                    "Fastfood" to "food burger eat takeaway",
                    "LunchDining" to "food meal eat",
                    "DinnerDining" to "food meal eat",
                    "BakeryDining" to "bakery bread pastry food",
                    "Icecream" to "dessert sweet food",
                    "TakeoutDining" to "food delivery takeaway",
                    "Store" to "shop retail market",
                    "Storefront" to "shop retail market store",
                    "ShoppingCart" to "shop buy cart checkout amazon",
                    "ShoppingBag" to "shop buy bag store",
                    "ShoppingBasket" to "shop buy basket groceries",
                    "LocalMall" to "shop shopping retail",
                    "LocalAtm" to "cash money bank withdraw",
                    "Atm" to "cash money bank withdraw",
                    "Receipt" to "bill invoice payment",
                    "Calculate" to "calculator math numbers",
                    "Loyalty" to "rewards points card membership",
                    "Redeem" to "gift reward coupon voucher",
                    "Sell" to "sale discount price offer",

                    // Work / money
                    "Work" to "job office briefcase career",
                    "WorkHistory" to "job office career resume",
                    "BusinessCenter" to "work office briefcase",
                    "AccountBalance" to "bank finance money",
                    "AccountBalanceWallet" to "wallet money finance pay",
                    "Wallet" to "money finance pay purse",
                    "CreditCard" to "pay card payment money",
                    "Payments" to "pay money finance transfer",
                    "AttachMoney" to "money dollar cash pay",
                    "Savings" to "money piggy bank finance",
                    "CurrencyBitcoin" to "crypto bitcoin money",
                    "CurrencyExchange" to "forex currency money convert",
                    "Analytics" to "stats chart data metrics",
                    "TrendingUp" to "growth chart stocks up",
                    "TrendingDown" to "decline chart stocks down",
                    "PieChart" to "stats chart data",
                    "BarChart" to "stats chart data",
                    "VolunteerActivism" to "donate charity heart help",
                    "School" to "education university college learn",

                    // Health / fitness / sports
                    "LocalHospital" to "health medical doctor emergency",
                    "LocalPharmacy" to "medicine health drugstore",
                    "MedicalServices" to "health doctor emergency ambulance",
                    "HealthAndSafety" to "health medical protect",
                    "Medication" to "medicine pills pharmacy",
                    "Vaccines" to "vaccine shot immunization",
                    "FitnessCenter" to "gym workout exercise weights",
                    "Spa" to "relax wellness massage",
                    "SelfImprovement" to "yoga meditation wellness mindfulness",
                    "MonitorHeart" to "health heart rate fitness",
                    "Pool" to "swim swimming water",
                    "Hiking" to "walk trail outdoors trek",
                    "SportsSoccer" to "football soccer sport",
                    "SportsBasketball" to "basketball sport",
                    "SportsTennis" to "tennis sport",
                    "SportsEsports" to "gaming game controller esport",
                    "SportsFootball" to "american football sport",
                    "Gamepad" to "game gaming controller play",
                    "VideogameAsset" to "game gaming controller play",
                    "Casino" to "gambling dice poker",
                    "Celebration" to "party confetti birthday",
                    "Cake" to "birthday dessert party",

                    // People / social
                    "Person" to "user profile account contact",
                    "Group" to "people users team community",
                    "Groups" to "people users team community",
                    "ManageAccounts" to "user profile settings people",
                    "Badge" to "id identity card name",
                    "SupervisorAccount" to "admin user manager people",
                    "Favorite" to "heart like love favourite",
                    "FavoriteBorder" to "heart like love favourite",
                    "Bookmark" to "save favourite pin later",
                    "BookmarkBorder" to "save favourite pin later",
                    "Star" to "favourite favorite rating highlight",
                    "StarBorder" to "favourite favorite rating",
                    "ThumbsUpDown" to "like dislike rating vote feedback",

                    // Create / tools
                    "Palette" to "art color paint design",
                    "Brush" to "paint art draw design",
                    "DesignServices" to "design art create",
                    "Architecture" to "design building blueprint",
                    "Code" to "developer programming terminal software",
                    "Terminal" to "code developer console shell",
                    "BugReport" to "debug issue error developer",
                    "BuildCircle" to "tools fix repair settings",
                    "Handyman" to "tools fix repair DIY",
                    "Construction" to "build tools work site",
                    "Science" to "lab experiment research",
                    "Lightbulb" to "idea tip invent",
                    "Extension" to "plugin add-on puzzle",

                    // Devices / connectivity
                    "Cloud" to "backup storage sync drive",
                    "CloudUpload" to "upload backup sync drive",
                    "CloudDownload" to "download backup sync drive",
                    "Wifi" to "internet wireless network connection",
                    "Bluetooth" to "wireless pair device",
                    "Router" to "wifi network modem internet",
                    "Computer" to "pc laptop desktop device",
                    "Tablet" to "ipad device",
                    "Devices" to "phone tablet computer gadgets",
                    "Keyboard" to "type input write",
                    "Mouse" to "pointer click computer",
                    "Watch" to "wearable time smartwatch",
                    "Print" to "printer paper document",
                    "Scanner" to "scan document copy",

                    // Privacy / system
                    "Lock" to "secure password privacy security",
                    "LockOpen" to "unlock open security",
                    "Visibility" to "show eye see visible",
                    "VisibilityOff" to "hide eye private invisible",
                    "Fingerprint" to "biometric unlock security",
                    "Key" to "password unlock security",
                    "Password" to "login secret security key",
                    "Notifications" to "alert bell reminder",
                    "NotificationImportant" to "alert bell warning reminder",
                    "DarkMode" to "night theme moon",
                    "LightMode" to "day theme sun bright",
                    "Security" to "lock shield privacy",
                    "Shield" to "security protect privacy",
                    "Settings" to "preferences gear options config",
                    "Search" to "find lookup query",
                    "Apps" to "launcher grid applications",
                    "Menu" to "hamburger navigation drawer",
                    "Category" to "folder group tags",
                    "Label" to "tag category marker",
                    "Tag" to "label category marker",
                    "Help" to "support question faq",
                    "HelpCenter" to "support question faq",
                    "QuestionMark" to "help support faq unknown",
                    "Support" to "help customer service",
                    "Login" to "signin enter account",
                    "Logout" to "signout exit leave account",
                    "Add" to "plus new create",
                    "Delete" to "remove trash bin erase",
                    "Close" to "dismiss cancel x",
                    "Cancel" to "close dismiss stop",
                    "CheckCircle" to "done ok success confirmed",
                    "Circle" to "dot bullet empty",

                    // Folders / files
                    "Folder" to "directory files documents",
                    "FolderOpen" to "directory files documents",
                    "FolderShared" to "directory files share collaboration",
                    "CreateNewFolder" to "directory files new",
                    "Inventory" to "stock warehouse boxes package",

                    // Nature / home life
                    "Pets" to "animal dog cat",
                    "Eco" to "green environment leaf nature",
                    "Nature" to "outdoors tree forest",
                    "Yard" to "garden outdoors grass",
                    "Park" to "outdoors nature recreation",
                    "BeachAccess" to "vacation sea sand umbrella",
                    "ChildCare" to "baby kids family",
                    "LocalLaundryService" to "wash clothes laundry",
                    "CleaningServices" to "clean house chores",
            )
}
