#!/usr/bin/env python3
"""Generate MaterialShippedOutlinedIcons.kt + MaterialPickerAllowlist.kt.

Picker icons are a curated allowlist (scripts/icon_picker_allowlist.txt), not the full
Material catalog. The shipped map also includes every Icons.Outlined.* used by
legacyAliases so stored snake_case keys keep resolving. Replaces reflection + blanket
ProGuard keep so R8 can strip the rest of material-icons-extended.

Run from repo root after updating the allowlist / full index / categories:
  python3 scripts/gen_shipped_outlined_icons.py \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconIndex.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialOutlinedIconCategories.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialShippedOutlinedIcons.kt \\
    app/src/main/java/com/lu4p/fokuslauncher/ui/components/generated/MaterialPickerAllowlist.kt
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ALLOWLIST_PATH = ROOT / "scripts" / "icon_picker_allowlist.txt"

# Icons.Outlined.* basenames from legacyAliases in MinimalIcons.kt (send uses AutoMirrored — skip).
LEGACY_OUTLINED = frozenset(
    {
        "Circle",
        "Apps",
        "Menu",
        "Category",
        "Email",
        "Mail",
        "Call",
        "Phone",
        "Contacts",
        "Link",
        "Share",
        "MusicNote",
        "Videocam",
        "CameraAlt",
        "Photo",
        "Image",
        "PlayArrow",
        "Palette",
        "Book",
        "Newspaper",
        "Headset",
        "Home",
        "Map",
        "Place",
        "LocationOn",
        "Directions",
        "Flight",
        "Alarm",
        "Timer",
        "CalendarMonth",
        "Event",
        "Person",
        "Favorite",
        "FavoriteBorder",
        "Bookmark",
        "BookmarkBorder",
        "VolunteerActivism",
        "Work",
        "Folder",
        "Code",
        "Settings",
        "AccountBalance",
        "ShoppingCart",
        "ShoppingBag",
        "Restaurant",
        "Gamepad",
        "Star",
        "StarBorder",
        "Cloud",
        "Search",
        "Close",
        "Add",
        "Delete",
        "ArrowBack",
        "CheckCircle",
        "ArrowForward",
        "ChevronRight",
        "Logout",
        "Cancel",
        "Notifications",
        "Lock",
        "DarkMode",
        "Language",
        "Translate",
    }
)


def load_index(index_path: str) -> list[str]:
    text = open(index_path, encoding="utf-8").read()
    return re.findall(r'^        "([^"]+)",?$', text, re.MULTILINE)


def load_allowlist(path: Path = ALLOWLIST_PATH) -> list[str]:
    names: list[str] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        names.append(line)
    # Stable unique order (file order, first wins).
    seen: set[str] = set()
    ordered: list[str] = []
    for name in names:
        if name in seen:
            continue
        seen.add(name)
        ordered.append(name)
    return ordered


def write_allowlist_kt(out_path: str, allowlist: list[str]) -> None:
    lines = [
        "package com.lu4p.fokuslauncher.ui.components.generated",
        "",
        "// Generated by scripts/gen_shipped_outlined_icons.py from scripts/icon_picker_allowlist.txt — do not edit by hand.",
        "internal object MaterialPickerAllowlist {",
        "",
        "    /** Curated outlined glyph names offered in icon pickers. */",
        "    @JvmField",
        "    val NAMES: Set<String> = setOf(",
    ]
    for n in sorted(allowlist):
        lines.append(f'        "{n}",')
    lines.append("    )")
    lines.append("}")
    lines.append("")
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")


def write_shipped_kt(out_path: str, shipped: list[str]) -> None:
    lines = [
        '@file:Suppress("DEPRECATION")',
        "",
        "package com.lu4p.fokuslauncher.ui.components.generated",
        "",
        "// Generated by scripts/gen_shipped_outlined_icons.py — do not edit by hand.",
        "// Outlined icons included in the APK: curated picker allowlist + legacy Icons.Outlined aliases.",
        "import androidx.compose.material.icons.Icons",
        "import androidx.compose.material.icons.outlined.*",
        "import androidx.compose.ui.graphics.vector.ImageVector",
        "import java.util.TreeMap",
        "",
        "internal object MaterialShippedOutlinedIcons {",
        "",
        "    /** Sorted outlined glyph names shipped in the app (subset of MaterialIcons extended). */",
        "    @JvmField",
        "    val SHIPPED_NAMES: List<String> = listOf(",
    ]
    for n in shipped:
        lines.append(f'        "{n}",')
    lines.append("    )")
    lines.append("")
    lines.append("    @JvmField")
    lines.append("    val byName: Map<String, ImageVector> = run {")
    lines.append("        val m = TreeMap<String, ImageVector>()")
    for n in shipped:
        lines.append(f'        m["{n}"] = Icons.Outlined.{n}')
    lines.append("        m")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 5:
        print(__doc__)
        sys.exit(2)
    index_path, _categories_path, shipped_out, allowlist_out = sys.argv[1:5]
    index_names = set(load_index(index_path))
    allowlist = load_allowlist()
    unknown = [n for n in allowlist if n not in index_names and n not in LEGACY_OUTLINED]
    if unknown:
        print("Allowlist names not in MaterialOutlinedIconIndex or LEGACY_OUTLINED:", file=sys.stderr)
        for n in unknown:
            print(f"  {n}", file=sys.stderr)
        sys.exit(1)

    pickable = set(allowlist)
    shipped = sorted(pickable | LEGACY_OUTLINED)
    write_allowlist_kt(allowlist_out, allowlist)
    write_shipped_kt(shipped_out, shipped)
    print(
        f"Wrote {len(shipped)} shipped icons to {shipped_out} "
        f"(allowlist={len(allowlist)}, legacy_extra={len(shipped) - len(pickable)})"
    )
    print(f"Wrote allowlist ({len(allowlist)}) to {allowlist_out}")


if __name__ == "__main__":
    main()
